# Stage 1 - the build process

FROM node:8 as build

WORKDIR /var/tic-tac-toe

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2 - the production environment

FROM nginx:1.15-alpine

COPY nginx.default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /var/tic-tac-toe/dist /usr/share/nginx/html

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
